"""
Auto-Keka licensing — offline license-key verification.

A license key is `base64url(payload) + "." + base64url(signature)`, where the
signature is Ed25519 over the payload, made with a PRIVATE key that only the
seller has (see tools/gen_license.py). This module ships the matching PUBLIC key
only, so the app can verify a key with no server and no internet — but nobody can
forge a key without the private key.

Payload JSON: {"n": name, "e": email, "x": expiry_epoch (0 = perpetual), "p": plan}
"""

import os
import json
import time
import base64

# Store the key in the stable per-user data folder (survives across runs even
# when the app is a compiled one-file binary). Falls back to the code dir if
# keka_common isn't importable (e.g. running this module standalone).
try:
    from keka_common import DATA_DIR
except Exception:
    DATA_DIR = os.path.dirname(os.path.abspath(__file__))
LICENSE_FILE = os.path.join(DATA_DIR, "license.key")

# The seller's PUBLIC key (hex, 32 bytes). Generated by tools/gen_license.py —
# replace this with YOUR public key before you ship. The private key stays secret.
PUBLIC_KEY_HEX = "70bc200bf2236f78693c49c8627e69d10796a533f09816149c378384cfd9c084"


def _b64d(s):
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def verify_key(key):
    """Return the license payload dict if the key is valid and unexpired, else None."""
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
        payload_b64, sig_b64 = key.strip().split(".", 1)
        payload = _b64d(payload_b64)
        sig = _b64d(sig_b64)
        pub = Ed25519PublicKey.from_public_bytes(bytes.fromhex(PUBLIC_KEY_HEX))
        pub.verify(sig, payload)          # raises on a bad/forged signature
        data = json.loads(payload)
        exp = data.get("x", 0)
        if exp and time.time() > exp:      # expired
            return None
        return data
    except Exception:
        return None


def load_license():
    """The stored key (or the KEKA_LICENSE env var, handy for testing)."""
    if os.path.exists(LICENSE_FILE):
        try:
            with open(LICENSE_FILE, encoding="utf-8") as f:
                return f.read().strip()
        except (OSError, ValueError):
            pass
    return os.environ.get("KEKA_LICENSE", "")


def save_license(key):
    with open(LICENSE_FILE, "w", encoding="utf-8") as f:
        f.write(key.strip())
    try:
        os.chmod(LICENSE_FILE, 0o600)
    except OSError:
        pass


def license_info():
    """The validated payload for the currently stored key, or None."""
    return verify_key(load_license())


def is_licensed():
    return license_info() is not None
